# Generated by Django 4.1.2 on 2022-10-21 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("chapter_school", models.CharField(max_length=50)),
                ("city_state", models.CharField(max_length=50)),
                ("original_founding_date", models.DateField()),
                ("recharter_date", models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=25)),
                ("chapter", models.CharField(default="null", max_length=10)),
                ("nickname", models.CharField(max_length=20)),
                ("crossing_chapter", models.CharField(default="null", max_length=10)),
                ("crossing_semester", models.CharField(max_length=6)),
                ("crossing_number", models.CharField(max_length=3)),
                ("tree", models.CharField(max_length=20)),
                ("line_number", models.IntegerField(verbose_name=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AC", "Active"),
                            ("AL", "Alumnae"),
                            ("DE", "Deceased"),
                        ],
                        default="AC",
                        max_length=2,
                    ),
                ),
                (
                    "big_sister",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.sister",
                    ),
                ),
                ("little_sister_crossed", models.ManyToManyField(to="main_app.sister")),
            ],
        ),
    ]
