# Generated by Django 4.1.2 on 2022-10-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "main_app",
            "0003_remove_sister_crossing_number_sister_crossing_year_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="sister",
            name="crossing_year",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="sister",
            name="line_number",
            field=models.IntegerField(),
        ),
    ]
