# Generated by Django 4.1.2 on 2022-10-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0004_alter_sister_crossing_year_alter_sister_line_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sister",
            name="crossing_year",
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name="sister",
            name="line_number",
            field=models.IntegerField(max_length=3),
        ),
    ]
