# Generated by Django 4.1.2 on 2022-10-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0005_alter_sister_crossing_year_alter_sister_line_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sister",
            name="crossing_year",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="sister",
            name="line_number",
            field=models.IntegerField(null=True),
        ),
    ]
