# Generated by Django 4.1.2 on 2022-10-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0007_alter_nickname_request_name_alter_sister_big_sister"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sister",
            name="little_sister_crossed",
            field=models.ManyToManyField(blank=True, to="main_app.sister"),
        ),
    ]
