# Generated by Django 4.1.2 on 2022-10-21 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0009_alter_sister_crossing_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sister",
            name="little_sister_crossed",
            field=models.ManyToManyField(blank=True, null=True, to="main_app.sister"),
        ),
    ]
