# Generated by Django 4.1.2 on 2022-10-21 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0010_alter_sister_little_sister_crossed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sister",
            name="big_sister",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main_app.sister",
            ),
        ),
        migrations.AlterField(
            model_name="sister",
            name="little_sister_crossed",
            field=models.ManyToManyField(blank=True, to="main_app.sister"),
        ),
    ]
