# Generated by Django 4.1.2 on 2022-10-22 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0011_alter_sister_big_sister_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sister",
            name="chapter",
        ),
        migrations.RemoveField(
            model_name="sister",
            name="crossing_chapter",
        ),
    ]
