# Generated by Django 4.1.2 on 2022-10-22 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0012_remove_sister_chapter_remove_sister_crossing_chapter"),
    ]

    operations = [
        migrations.AddField(
            model_name="sister",
            name="chapter",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="active_chapter",
                to="main_app.chapter",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sister",
            name="crossing_chapter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crossing_chapter",
                to="main_app.chapter",
            ),
        ),
    ]
