# Generated by Django 4.1.2 on 2022-10-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0013_sister_chapter_sister_crossing_chapter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="recharter_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
