# Generated by Django 4.1.2 on 2022-10-22 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0014_alter_chapter_recharter_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pnm",
            name="chapter",
        ),
        migrations.AlterField(
            model_name="pnm",
            name="process_chapter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="process_chapter",
                to="main_app.chapter",
            ),
        ),
    ]
