# Generated by Django 4.1.2 on 2022-10-22 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0015_remove_pnm_chapter_alter_pnm_process_chapter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sister",
            name="little_sister_crossed",
        ),
    ]
