# Generated by Django 4.1.2 on 2022-10-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0016_remove_sister_little_sister_crossed"),
    ]

    operations = [
        migrations.AddField(
            model_name="sister",
            name="crossing_class",
            field=models.CharField(
                choices=[
                    ("01", "Alpha"),
                    ("02", "Beta"),
                    ("03", "Gamma"),
                    ("04", "Delta"),
                    ("05", "Epsilon"),
                    ("06", "Zeta"),
                    ("07", "Eta"),
                    ("08", "Theta"),
                    ("09", "Iota"),
                    (10, "Lambda"),
                    (11, "Mu"),
                    (12, "Nu"),
                    (13, "Xi"),
                    (14, "Omicron"),
                    (15, "Pi"),
                    (16, "Rho"),
                    (17, "Sigma"),
                    (18, "Tau"),
                    (19, "Upsilon"),
                    (20, "Phi"),
                    (21, "Chi"),
                    (22, "Psi"),
                    (23, "Omega"),
                ],
                default="01",
                max_length=2,
            ),
        ),
    ]
