# Generated by Django 4.1.2 on 2022-10-24 01:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0018_alter_sister_crossing_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="nickname_request",
            name="nickname_approval_status",
            field=models.CharField(
                choices=[
                    ("RE", "Requested"),
                    ("AP", "Approved"),
                    ("QU", "Queued"),
                    ("DE", "Denied"),
                ],
                default="RE",
                max_length=2,
                verbose_name="Nickname Approval Status",
            ),
        ),
        migrations.AddField(
            model_name="nickname_request",
            name="requestor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main_app.sister",
            ),
        ),
        migrations.AlterField(
            model_name="nickname_request",
            name="req_date",
            field=models.DateTimeField(
                auto_created=True,
                default=datetime.datetime(
                    2022, 10, 24, 1, 4, 56, 850555, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date requested",
            ),
        ),
    ]
