# Generated by Django 4.1.2 on 2022-10-24 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0020_chapter_user_nickname_request_user_pnm_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chapter",
            name="user",
        ),
        migrations.RemoveField(
            model_name="nickname_request",
            name="user",
        ),
        migrations.RemoveField(
            model_name="pnm",
            name="user",
        ),
        migrations.RemoveField(
            model_name="sister",
            name="user",
        ),
        migrations.AlterField(
            model_name="nickname_request",
            name="req_date",
            field=models.DateTimeField(
                auto_created=True,
                default=datetime.datetime(
                    2022, 10, 24, 19, 10, 28, 552999, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date requested",
            ),
        ),
    ]
